### PR TITLE
Binary integers

### PR DESCRIPTION
**Pull request by QGarchery**
This PR proposes an implementation of binary integers and some of their properties in the file `Z.lp`.

Along the way we:
- defined positive binary integers in `Pos.lp`, they are at the core of the definition of binary integers
- defined the comparison data structure (a type with exactly 3 elements) in `Comp.lp`, needed to provide clean comparison functions over binary integers
- defined the other 'deep' representations of the quantifiers of CoC in `CoC.lp`, needed to prove a 'natlike' induction principle on binary integers, see `Pos.ind_positive_peano`

EDIT : Thanks @amelieled for updating the proofs to the new syntax ! (see https://github.com/QGarchery/lib/pull/1)

### CODE REVIEW

**Comment by fblanqui** [comment]
Thank you very much @QGarchery for your PR but, as you will guess, it will take some time before I can review it. Thanks for your patience! Note that this PR will be useful to @gabrielhdt to represent PVS integers in LP in an efficient way.

**Comment by QGarchery** [comment]
Sure, no problem ! Even better if there are plans to use this in the future !

Don't hesitate to change the code or ask any question concerning this PR

**Comment by QGarchery** [comment]
The formalization has been updated to the new syntax, thanks to @amelieled :)

Can you run the workflow on this PR @fblanqui ? I tested it locally and it seems to go through.

Also that would be awesome if we could merge this PR, and I would be happy to help if needed

**Comment by fblanqui** [comment]
Hi @QGarchery . It would be nice to get rid of CoC.lp. Do you really need such a strong theory? It should be possible to check your formalization in FOL. A first step could be to remove the symbols and rules of CoC.lp that are not necessary, and identify the places whether the remaining symbols and rules are used.

**Comment by QGarchery** [comment]
Hi @fblanqui ! CoC is needed for the proof of `ind_positive_peano` which is the basis of the following proofs. As a side note I really like the proof of this result (it's not mine). Not sure how we would do without it. 

Also CoC seems like a nice addition to this library, showing the expressive power of lambdapi. Users can still leave it out of their development and include only the first order logic if they want. Do you feel like we should take more steps to make first order logic stand out more compared to CoC ?

**Comment by fblanqui** [comment]
This PR doesn't work with lambdapi 2.2.0 but with lambdapi 2.2.1 and master...

**Comment by fblanqui** [comment]
Ultimately, we should try to express this library in the system U. See https://github.com/Deducteam/lambdapi-logics/tree/master/U. Perhaps you just need HOL, that is, to add a code for propositions and functions? See https://github.com/Deducteam/lambdapi-logics/blob/master/U/Arrow.lp and https://github.com/Deducteam/lambdapi-logics/blob/master/U/Impredicativity.lp. What could be interesting is to take ind_positive_peano as axiom in the development and define it in a separate file. This would isolate the axioms necessary to prove it.

**Comment by fblanqui** [comment]
I don't know why CI fails for a few days now. I opened https://github.com/ocaml/setup-ocaml/issues/630. Help is welcome!

**Comment by fblanqui** [comment]
@gabrielhdt: I would like to replace s by +1 in postfix notation to do like in ssr but then I get typing problems in the first lemma n +1 ≠ 0 where  ≠ is infix. It seems that n +1  ≠ 0 is not parsed properly. Do I do anything wrong? Could you please have a look at this?

**Comment by gabrielhdt** [comment]
Hi @fblanqui, could you please provide the full term, as well as the error message? Could you provide as well the priorities you have set on `\ne` and `+1`, or could you provide a link to your `Nat.lp`?

**Comment by fblanqui** [comment]
```
git add remote garchery git@github.com:QGarchery/lib.git
git fetch garchery
git checkout -b binint garchery/master
```
Then replace "s" by "+1" and add after the definition of +1:
```
notation +1 postfix 100;
```
You get:
```
inductive ℕ : TYPE ≔
| 0 : ℕ
| +1 : ℕ → ℕ;
notation +1 postfix 100;
...
```
First thing strange:
```
rule is0 0 ↪ true
with is0 (+1 _) ↪ false;
```
does not fail while we should write
```
with is0 (_ +1) ↪ false;
```
But the main problem comes with the first lemma:
```
opaque symbol s≠0 [n] : π (n +1 ≠ 0) ≔
begin
  assume n h; refine ind_eq h (λ n, istrue(is0 n)) top
end;
```
I get:
```
[/home/blanqui/src/lib/Nat.lp:122:2-12] Not a typing goal.
```
Indeed, the first goal is:
```
n: Π y: (ℕ → ℕ), ?35.[y]
------------------------------
?35.[+1] ≡ ℕ
```
Note that ≠ is defined in Eq as follows:
```
symbol ≠ [a] (x y : τ a) ≔ ¬ (x = y); notation ≠ infix 10; // \neq
```

**Comment by gabrielhdt** [comment]
So I see two problems,
1. parsing does not fail when a postfix operator is used prefix
2. apparently parsing behaves unexpectedly when a postfix operator is on the left of an infix one.

I'll have a look.

**Comment by fblanqui** [comment]
Thanks!

**Comment by fblanqui** [comment]
Thanks @QGarchery for your PR. I succeeded in removing the dependency to CoC.

**Comment by QGarchery** [comment]
Awesome ! Thank you @fblanqui !

**Pull request merged**
